const SETLIST_DOCUMENTS = SpreadsheetApp.getActive()
    .getSheetByName("Setlist pdfs");

const SETLIST_DOCUMENTS_MENU_ROWS = 1;

const DOC_DATA_ID_COL = 0;
const DOC_SHEET_ID_COL = DOC_DATA_ID_COL + 1;

const DOC_DATA_SETLIST_ID_COL = 1;
const DOC_SHEET_SETLIST_ID_COL = DOC_DATA_SETLIST_ID_COL + 1;

const DOC_DATA_SETLIST_PDF_NAME_COL = 2;
const DOC_SHEET_SETLIST_PDF_NAME_COL = DOC_DATA_SETLIST_PDF_NAME_COL + 1;

const DOC_DATA_SETLIST_PART_COL = 3;
const DOC_SHEET_SETLIST_PART_COL = DOC_DATA_SETLIST_PART_COL + 1;

const DOC_DATA_SETLIST_URL_COL = 4;
const DOC_SHEET_SETLIST_URL_COL = DOC_DATA_SETLIST_URL_COL + 1;

const DOC_DATA_SETLIST_GOOGLE_ID_COL = 5;
const DOC_SHEET_SETLIST_GOOGLE_ID_COL = DOC_DATA_SETLIST_GOOGLE_ID_COL + 1;
